### PR TITLE
Make modules more generic, Client connection state callback

### PR DESCRIPTION
**Pull request by kevinkk525**
Some improvements for making the module more generic:
- removing references to local.py inside client.py
- added reference to local.py to c_app
- made client.Client() creation use more args (server, port, ...)
- added a callback coro to the client, that is called everytime the connection state changes, as a higher level application might be interested in knowing this. (Maybe the server restarted and needs some information again, ...)
- generelly changed import statements to import from current directory (if file structure is used as in the repo) and on Exception use normal import statement (for those just copying needed files).
- removed all .mpy files as they would have to be recreated anyway
- moved server code into separate package

Thought this was a good way to go forward, making the client module more generic without the need to use the local.py to make it independent. The c_app.py as a higher level application should be in control of all configuration options.

The Client callback on connection change might come in handy for higher level applications as they might need to (re)send some data to the server if the server restarted or do other stuff.

The rest is mostly "cleanup" to my preferences: more dynamic way of importing modules of this repository and moving server files into separate package.

### CODE REVIEW

**Comment by peterhinch** [comment]
Some of these changes reflect differences in our coding styles. I regard Python packages as a complication too far for "micro" applications and have not used them in any of my efforts. I'm of two minds whether to change this stance.

The callback coro on state change is an excellent idea.

My import of `local.py` into `Client.py` rather than into the application is unconventional, but was a design decision based on the assumption that the `Client` instance would be a singleton. It simplifies the application code; I can't envisage an ESP8266 running more than one `Client` concurrently. If you have a use-case in mind for multiple `Client` instances, and have tested its feasibility, my enthusiasm for this would increase :)

If we keep it as a singleton I should explicitly state this in the docs.

To keep you in the loop I am currently working on the extension to the Pyboard, in particular ensuring it is resilient if the ESP8266 crashes (not that it should). I then plan to ensure that the server code is portable to MicroPython. I don't foresee a particular use-case but it seems like a good idea.

I'll then revisit the Client code and implement any changes we settle on.

**Comment by peterhinch** [comment]
Two thoughts regarding the state change coro with a view to making it more general. These are just ideas - there may be reasons against.

It can be useful to provide for args to such functions (e.g. an `Led` instance).

If you look at my [asyn.py](https://github.com/peterhinch/micropython-async/blob/7161dade92115a16415ed92404e2ca0bba4b96b8/asyn.py#L46) there is a way to enable a function to be passed which can be a coro or a method (bound or not). An example of its use [is here](https://github.com/peterhinch/micropython-async/blob/7161dade92115a16415ed92404e2ca0bba4b96b8/aswitch.py#L80) documented [here](https://github.com/peterhinch/micropython-async/blob/master/DRIVERS.md).

**Comment by kevinkk525** [comment]
**Packages**
I understand that you want to keep it simple by not using packages in micropython. Let me explain my point of view on this difference, maybe it helps but maybe it will just make the differences of our coding style more solid which is also ok as I won't bring up any changes in that direction again in that case.

Disadvantages of not using packages:
- you have to copy every file you need into the root directory of your microcontroller/ports directory
- you can easily lose track of where files are from making updating them more difficult
- you might not have any license and author information in the file as only the repository contained that information
- you don't know when a file gets updated because you'd have to manually compare them to the repo
- when looking at your repositories I often have to read the README repeatedly to understand which files are just examples and which ones are the actual libraries as everything is just in the same directory, sometimes even without an easy to understand filename.
- pushing a bigger project to github (like my pysmartnode) would be a lot more difficult as you include files from other authors (possibly without containing licence and author) and would have to name the sources in your README. Or push your project without these files and list them as dependencies making it more difficult for the user to use your project. 
- a bigger project like my [pysmartnode](https://github.com/kevinkk525/pysmartnode) would be a horrible mess without a package structure, having over 50 files in the root directory.

Advantages of having packages:
- miropython can handle them well
- structure is more transparent and you easily understand where a file belongs to
- you can include repositories in your project by clonging them/using a submodule making it transparent where the files are from, who's the author and licence (well I guess it should be MIT anyway as multiple licences could be problematic). 
You can also easily update these by updating the submodule/repo without manually copying all new files.
- you don't have a mess in your microcontroller directory and know which file belongs to what project
- it's easier for the user to include or remove your project as he does not need to search for all files that your project added
- your project can always have all dependencies (except uasyncio)


Is it ok for you to have packages in your repository to make the structure cleaner? If not then that's of course ok but the next question does not need an answer: Is it a good compromise to use an import statement like this (like I used) to enable bother coding styles to profit from your repositories:
```
try:
    from . import primitives as asyn 
except:
    import primitives as asyn
```
This allows people like me to use your repository as a package using relative imports while people like you can still put every file into the root directory and it will work.



**State change callback**
Thanks for your thoughts on this, I think that is a good idea but got me thinking:
As only one callback and args are used, these will be the same regardless of state. 
How to "inject" the current state if args for the callback are set? Like callback(<state>,*args)? 


**local.py**
I think you mostly missed my point about the *local.py* inclusion but I did not explain it well, sorry for that.
I don't think the esp8266 should handle more than one client, that would probably need a reimplementation of the outage detection to prevent multiple clients from constantly reconnecting to the wifi.
If you build a bigger project, you are likely to have more configuration options than the *local.py*, therefore it would be good to have the option to configure the module using your own configuration file that you use anyway instead of having to use the *local.py* additionally to your project specific configuration file. I like to have all configurations in one place and not having to look into library specific configuration file just to put my server-ip and port into it.


I'm really looking forward to the pyboard :)
Porting the server code to micropython could be interesting to eliminate the need of an external proxy for usage in a small environment. May be a small field of application but I can definitely think of one.

**Comment by peterhinch** [comment]
### State change callback
If you look at my examples in my micropython-async repo you'll see that I pass a callback/coro and a tuple of args (default `()`) as constructor args. When the function is called the mandatory state arg can be inserted before the user args:
```python
>>> def rats(a,b,c):
...     print(a,b,c)
... 
>>> z = (2,3)
>>> rats(99, *z)
99 2 3
>>> 
```
### Packages
I think you're probably right about this - I'm probably stuck in (very) old ways here. I'll consider it some more over the next few days.
### Config args
I'm also becoming convinced by this. My Pyboard work has an option for the ESP8366 to run a fixed binary firmware image. This therefore requires the config to be set at runtime by the Pyboard rather than from a fixed file baked into the image. Passing the config as constructor args is the neatest way to achieve this. However the idea of 'local.py' was also to promote consistency between multiple ESP8266 devices and the server. I anticipated a user creating the file and distributing it to each node, editing only the client ID. That way all other code files are unchanged between clients. But your solution still enables that approach.

**Comment by kevinkk525** [comment]
Thank you for the fast answers.

I'll implement the state change coro as proposed, I think this is a good approach.

Just for confirmation: "Please feel free to implement changes to code and directory structures exclusively for packages"
Does that *exclusively* mean that the code should only support being used as a package resulting in the following relative import statement?
```from . import primitives```

Ok I'll try to do it in the next days. I'm currently in the last bits of documenting a big server implementation.

**Comment by peterhinch** [comment]
Yes, you've convinced me :) I think we should go for packages. You have the experience of using them so please implement them as you think best.

Let's be consistent throughout the project and require that modules are installed correctly.

**Pull request closed without merging**
